// ===============================================
// extraChoices.js
//
// WHY THIS FILE EXISTS
// Every episode in storyData.js has 2 choices (the right one and
// one wrong one). This file adds TWO MORE choices to every
// episode, so each decision now has 4 options:
//   1. the original right choice          (from storyData.js)
//   2. the original wrong choice          (from storyData.js)
//   3. an extra tempting-but-wrong choice (added here)
//   4. a FUNNY choice, marked funny: true (added here)
//
// HOW IT WORKS
// - extraChoices[storyId][episodeNumber - 1] is a list of the two
//   extra choices for that episode: [ wrong, funny ].
// - applyExtraChoices() (at the bottom) pushes them into
//   storiesData, so story.html does not need to know about them.
// - The extra choices are always wrong (correct: false) and give 0
//   skill points. Their reaction is spoken by the same character
//   who reacts to the original wrong choice.
// - story.html shuffles the order of the buttons every time an
//   episode is shown, so the right answer can be in any position.
// - extraTranslations adds Hindi/English text for the one story
//   that has translations (doctor). Other stories fall back to the
//   original text, like the rest of the app does.
// ===============================================

const extraChoices = {
  doctor: [
    [ { text: "Patient ko pehle painkiller de do aur baaki tests baad mein karenge",
        reaction: "Riya, bina tests ke sirf painkiller dena chest pain mein khatarnaak ho sakta hai. Pehle ECG aur vitals, phir treatment." },
      { text: "Patient ko bolo 'Aap bas gehri saans lo, main YouTube par dekh leti hoon kya karna hai'",
        reaction: "Riya, YouTube pe sab kuch milta hai, par ER mein nahi! Patient ki jaan ka sawaal hai - pehle ECG aur vitals check karo.", funny: true } ],
    [ { text: "Ek aur random test order kar do aur dekhte hain kya aata hai",
        reaction: "Riya, bina soche sab tests karwana na patient ke liye theek hai na hospital ke liye. Confuse ho, toh senior se consult karo." },
      { text: "Sikka uchhaal kar decide karo - heads pe treatment A, tails pe treatment B",
        reaction: "Riya, medical decisions sikke se nahi, evidence aur seniors ki salah se hote hain! Sikka canteen mein chai ke liye rakho.", funny: true } ],
    [ { text: "Unhe bolo ki medical terms bahut mushkil hain, aap samajh nahi paoge",
        reaction: "Riya, mushkil baat ko aasaan bhasha mein samjhana hi doctor ka kaam hai. Shaanti se sach batao, jitna pakka ho utna." },
      { text: "Unhe ek chai pilao aur bolo ki chai ke saath tension apne aap chali jaati hai",
        reaction: "Riya, chai se dil ko sukoon milta hai, par family ko sahi jaankari chahiye. Pehle sach batao, chai baad mein.", funny: true } ],
    [ { text: "Pehle poori file aur insurance ka paperwork complete karwao, phir operation ki taiyari karo",
        reaction: "Riya, emergency mein paperwork baad mein - patient ki jaan pehle. Team ko turant alert karna zaroori hai." },
      { text: "Team ko WhatsApp group mein message karo aur blue tick ka wait karo",
        reaction: "Riya, WhatsApp pe blue tick ka wait karne se patient ka BP nahi sudharta! Emergency mein seedha call karo aur team ko alert karo.", funny: true } ],
    [ { text: "Thodi coffee peekar duty ke liye khud ko push karo, thakaan ko ignore karo",
        reaction: "Riya, thakaan ko coffee se dhakna rest nahi hota. Thakke doctor se galtiyan hoti hain - thodi der aaram karo." },
      { text: "OT ki table par let kar so jao, wahi sabse comfy jagah hai",
        reaction: "Riya, OT table patient ki hoti hai, doctor ka bed nahi! Rest room mein jao aur thoda aaram karo.", funny: true } ]
  ],
  paramedic: [
    [ { text: "Bheed se poochte raho ki kisne accident dekha, patient ko wahin chhod do",
        reaction: "Kabir, witness baad mein bhi mil jaate hain. Pehle scene secure karo aur patient ki jaan bachao." },
      { text: "Ambulance ka siren aur zor se bajao taaki bheed apne aap bhaag jaaye",
        reaction: "Kabir, siren se bheed ke kaan phatenge, par safety nahi milegi. Scene ko shaanti se secure karo.", funny: true } ],
    [ { text: "Ek saath saari machines lagakar dekhte hain kya kaam karti hai",
        reaction: "Kabir, bina order ke sab kuch lagana confusion badhata hai. Standard protocol se vitals stabilize karo." },
      { text: "Patient ko motivational speech do - 'Tum kar sakte ho!' - aur baaki sab bhool jao",
        reaction: "Kabir, hausla dena achhi baat hai, par oxygen aur vitals bhi zaroori hain! Pehle protocol follow karo.", funny: true } ],
    [ { text: "Sirf patient ka naam bata do, baaki ER staff khud dekh lega",
        reaction: "Kabir, incomplete handover mein important cheezein reh jaati hain. Poori jaankari clearly do." },
      { text: "Patient ki jaankari ek shayari mein sunao taaki ER staff yaad rakhe",
        reaction: "Kabir, shayari mast hai, par ER ko facts chahiye, kavita nahi! Clear aur complete jaankari do.", funny: true } ],
    [ { text: "Unhe bolo 'Aap bahar wait karo' aur bina kuch samjhaye door band kar do",
        reaction: "Kabir, ghabraye family ko akela chhod dena unka dar badhata hai. Shaant karke clear instructions do." },
      { text: "Family se bolo ki agar wo chillana band karein toh unhe siren bajane doge",
        reaction: "Kabir, siren bajana koi inaam nahi hai! Family ko shaant karo aur seedhe, saaf instructions do.", funny: true } ],
    [ { text: "Call jaldi le lo, rest baad mein ek hi baar lambi neend leke kar lenge",
        reaction: "Kabir, thaka hua paramedic galti kar sakta hai. Thodi der rest lo taaki agli call ke liye fresh raho." },
      { text: "Ambulance ki stretcher par hi so jao aur khud ko hi 'patient' bana lo",
        reaction: "Kabir, stretcher patient ke liye hai, tumhare liye nahi! Rest room mein thoda aaram karo, phir call lo.", funny: true } ]
  ],
  nurse: [
    [ { text: "Sabse pehle us patient se milo jis se baat karne mein maza aata hai",
        reaction: "Tanvi, priority patient ki zaroorat se tay hoti hai, pasand se nahi. Chart dekhkar decide karo." },
      { text: "Sab patients ko line mein khada karke 'Ek, do, teen' bol kar attendance lo",
        reaction: "Tanvi, ward school ki assembly nahi hai! Chart dekhkar sabse zyada zarooratmand patient ko pehle dekho.", funny: true } ],
    [ { text: "Unhe bed par hi rehne do, chalne ki koi zaroorat nahi",
        reaction: "Tanvi, operation ke baad dheere dheere chalna recovery ke liye zaroori hai. Support karke hausla badhao." },
      { text: "Unhe bolo ki chalne ki race lagate hain, jo jeetega usko chocolate milegi",
        reaction: "Tanvi, race nahi, dheere dheere! Buzurg patient ko support aur hausla chahiye, chocolate baad mein.", funny: true } ],
    [ { text: "Khud calculator par dosage check karke apne hisaab se badal do",
        reaction: "Tanvi, dosage badalna nurse ka kaam nahi. Doctor se turant confirm karo." },
      { text: "Dawai ko ek baar sungh kar dekho, agar theek lage toh de do",
        reaction: "Tanvi, dawai sungh kar dosage nahi pata chalta! Doctor se turant confirm karna hi sahi tareeka hai.", funny: true } ],
    [ { text: "Pehle kisi ko phone karke poochho ki kya karna hai, phir hi kuch karo",
        reaction: "Tanvi, seconds count karte hain. Training follow karke turant action lo aur saath mein help bulao." },
      { text: "Zor se 'Code Blue!' chillao aur phir sabke liye chai mangwao",
        reaction: "Tanvi, 'Code Blue' sahi hai, par chai ka time baad mein! Shaant rehkar training follow karo.", funny: true } ],
    [ { text: "Aaj ke baad thoda kam dhyan do, ab toh shift khatam ho rahi hai",
        reaction: "Tanvi, patient care shift ke ghante dekhkar nahi hoti. Har din utna hi dhyan dena hi commitment hai." },
      { text: "Sab patients ko 'Good night, sweet dreams' ka card dekar apni shift close karo",
        reaction: "Tanvi, pyaara idea hai, par asli commitment card se nahi, roz ke care se dikhta hai. Patient care ko hamesha priority do.", funny: true } ]
  ],
  cricketer: [
    [ { text: "Pehli ball se hi blind slog karo, shayad selectors ka dhyan jaye",
        reaction: "Arjun, andhadhund shot se out hone ka darr hai. Apna natural game khelo, runs khud aayenge." },
      { text: "Helmet pehen kar ulta khade ho jao, sabko lagega ki tum alag ho",
        reaction: "Arjun, alag dikhna aur alag khelna do alag baatein hain! Seedha khade ho aur natural game khelo.", funny: true } ],
    [ { text: "Bat ko zor se ghumao aur aankhein band kar lo",
        reaction: "Arjun, aankhein band karke koi bhi ball nahi khel sakta. Foot work sahi rakho aur ball dekho." },
      { text: "Bowler ko bolo 'Bhai, thoda dheere daalo, meri chai thandi ho rahi hai'",
        reaction: "Arjun, bowler tumhari chai ka nahi, tumhare wicket ka dushman hai! Ball ko dhyan se dekho.", funny: true } ],
    [ { text: "Dressing room chhod kar bahar chale jao aur baat karna band kar do",
        reaction: "Arjun, bhaagna solution nahi hai. Shaant rehkar baat samjhao aur team ke decision ko follow karo." },
      { text: "Senior ko cricket ke rules ki poori book padh kar sunao",
        reaction: "Arjun, book se bahas jeetne se team nahi jeetti! Shaanti se baat samjhao aur team decision follow karo.", funny: true } ],
    [ { text: "Ek painkiller khaakar khud hi check kar lo ki chal sakte ho ya nahi",
        reaction: "Arjun, painkiller se chot chhupti hai, theek nahi hoti. Physio ko dikhao aur unki advice follow karo." },
      { text: "Pair par bandage ki jagah paani ki bottle bandh lo, thanda rahega",
        reaction: "Arjun, bottle bandhne se chot theek nahi hoti! Physio ko dikhao aur unki advice maano.", funny: true } ],
    [ { text: "Sochte raho ki agar out ho gaye toh sab kya kahenge",
        reaction: "Arjun, aise sochne se pressure badhta hai. Ek-ek ball par focus karo." },
      { text: "Bowler ko dekh kar smile karo aur bolo 'Bhai, ek chhakka toh banta hai'",
        reaction: "Arjun, smile achhi hai, par ball ko dekhna zyada zaroori hai! Ek-ek ball par focus karo.", funny: true } ]
  ],
  footballer: [
    [ { text: "Sirf apni performance ki tension lo aur kisi teammate ko pass hi mat do",
        reaction: "Kiran, football team game hai. Natural game khelo aur confidence rakho." },
      { text: "Ball ko sar par rakh kar Ronaldo jaisa celebration karo, pehle hi goal kiye bina",
        reaction: "Kiran, celebration goal ke baad hota hai, pehle nahi! Apna natural game khelo.", funny: true } ],
    [ { text: "Coach ki baat sun lo, par game mein apni marzi se khelo",
        reaction: "Kiran, strategy sirf sunna kaafi nahi, follow karna zaroori hai. Team ke fayde ke liye coach ka plan maano." },
      { text: "Goalkeeper ki jagah khud goal post mein khade ho jao aur attack sochte raho",
        reaction: "Kiran, goal post mein khade hokar attack nahi hota! Coach ki strategy team ke fayde ke liye follow karo.", funny: true } ],
    [ { text: "Team ko bolo ki ab kuch nahi ho sakta, agla season dekhenge",
        reaction: "Kiran, haar ke baad hausla girana haar ko aur badhata hai. Team ko positive rakhne ke liye encourage karo." },
      { text: "Sabko bolo ki ab se sab kuch ulta karenge - ulta jersey, ulte shoes",
        reaction: "Kiran, ulte shoes se jeet nahi aati! Team ko encourage karo aur mil kar practice par focus karo.", funny: true } ],
    [ { text: "Half-time tak chup raho, phir dekhte hain ki kya karna hai",
        reaction: "Kiran, chot ko wait karne se wo badhti hai. Turant coach ya physio ko batao." },
      { text: "Referee ko bolo ki ankle ko red card de do, wahi sab galti ka karan hai",
        reaction: "Kiran, ankle ko card nahi, physio ko dikhana padta hai! Turant chot ke baare mein batao.", funny: true } ],
    [ { text: "Aankhein band karke kick maar do, jo hoga dekha jayega",
        reaction: "Kiran, aankhein band karke goal nahi hote. Shaant rehke penalty par focus karo." },
      { text: "Goalkeeper ko kaho ki 'Bhai, tu side hat ja, main zor se maar raha hoon'",
        reaction: "Kiran, goalkeeper tumhari baat nahi maanega! Shaant rehke penalty par focus karo.", funny: true } ]
  ],
  basketball: [
    [ { text: "Sirf 3-pointers hi maaro, baaki sab kuch ignore karo",
        reaction: "Zara, ek hi skill se team nahi banti. Apne basics aur teamwork par focus karo." },
      { text: "Ball ko ungli par ghumate hue puri court mein nach kar dikhao",
        reaction: "Zara, nachna dance floor par hota hai, court par nahi! Basics aur teamwork par focus karo.", funny: true } ],
    [ { text: "Us player ko dhakka de kar rasta banao",
        reaction: "Zara, foul se game bigadta hai. Team ko pass karo aur team play par focus karo." },
      { text: "Opponent ke saath handshake karke request karo ki wo apni jagah se hat jaye",
        reaction: "Zara, opponent aise nahi hatta! Team ko pass karo aur team play se rasta banao.", funny: true } ],
    [ { text: "Coach se shikayat karo ki teammate hi galat hai",
        reaction: "Zara, seedhe baat karne se mamla suljhta hai. Teammate se shaant rehkar baat karo." },
      { text: "Locker room mein taali bajakar sabko apni style ka demo dikhao",
        reaction: "Zara, demo se tension nahi jaati! Teammate ki baat sunkar shaanti se samjho.", funny: true } ],
    [ { text: "Ice lagakar ek ghanta baad practice par laut aao",
        reaction: "Zara, finals se pehle chot ko halke mein na lo. Physio se check karwao aur unki advice follow karo." },
      { text: "Ankle par sticker laga lo aur bolo ki ye 'magic tape' hai",
        reaction: "Zara, sticker se chot theek nahi hoti! Turant physio se check karwao.", funny: true } ],
    [ { text: "Ball kisi ko bhi pass kar do aur bas jaldi se court se hat jao",
        reaction: "Zara, moment se bhaagna solution nahi. Shaant rehkar apna practiced shot lagao." },
      { text: "Ball ko dono haathon se peeche se phenko aur aankhein band kar lo",
        reaction: "Zara, peeche se phenkne se koi point nahi milta! Shaant rehkar apna practiced shot lagao.", funny: true } ]
  ],
  it: [
    [ { text: "Internet se koi bhi code copy karke chipka do",
        reaction: "Yash, bina samjhe code copy karna naye bug la sakta hai. Pehle poora code padhkar samjho." },
      { text: "Computer ko band karke dobara on karo, shayad bug khud bhaag jaye",
        reaction: "Yash, 'off and on' har baar kaam nahi karta, kabhi kabhi code ko samajhna padta hai! Pehle code padho.", funny: true } ],
    [ { text: "Team ko batao ki project 100% ready hai, chahe abhi adhoora ho",
        reaction: "Yash, jhooth bolne se baad mein badi problem hoti hai. Client ko sach batao aur extra time maango." },
      { text: "Client ko ek pyaara sa 'sorry' wala emoji bhejo aur baat khatam",
        reaction: "Yash, emoji se deadline nahi badhti! Sach batao aur client se thoda extra time maango.", funny: true } ],
    [ { text: "Demo cancel kar do aur bolo ki client ko din galat pata tha",
        reaction: "Yash, bahane banane se bug fix nahi hota. Console logs aur error messages check karo." },
      { text: "Screen par bade akshar mein 'Loading...' likh do taaki kisi ko pata na chale",
        reaction: "Yash, 'Loading...' likhne se crash theek nahi hota! Console logs check karo aur asli problem dhoondo.", funny: true } ],
    [ { text: "Ankit Sir se bolo ki wo hi decide kar dein, main kuch nahi bolunga",
        reaction: "Yash, apni baat rakhna zaroori hai. Dono approach ke pros/cons list karke team se discuss karo." },
      { text: "Sikka uchhaal kar approach decide kar lo",
        reaction: "Yash, code sikke se nahi, logic se decide hota hai! Pros/cons list karke team se discuss karo.", funny: true } ],
    [ { text: "Ek ghante ki neend lekar seedhe agle project ki planning mein lag jao",
        reaction: "Yash, lagatar kaam se burnout hota hai. Ek din ki chutti lo aur fresh hokar wapas aao." },
      { text: "Chutti mein bhi laptop ko saath le jao aur usse 'Happy Launch' bolo",
        reaction: "Yash, chutti mein laptop ko bhi chutti do! Ek din ka aaram lo aur fresh hokar wapas aao.", funny: true } ]
  ],
  startup: [
    [ { text: "Pehle ek badi team hire karo aur ek saal baad app launch karo",
        reaction: "Arnav, bada plan banane se pehle idea test karna zaroori hai. Chhota MVP bana kar real users pe test karo." },
      { text: "App ka naam sirf emoji rakh do aur users se guess karwao",
        reaction: "Arnav, naam achha hai, par pehle product test karna zaroori hai! Chhota MVP bana kar real users pe test karo.", funny: true } ],
    [ { text: "Sirf apne dreams aur passion ki baat karo, numbers ki zaroorat nahi",
        reaction: "Arnav, passion zaroori hai par investor ko numbers bhi chahiye. Data ke saath confident pitch do." },
      { text: "Investors ko free samosa khilao aur pitch kal par taal do",
        reaction: "Arnav, samosa se investment nahi milta! Data aur numbers ke saath confident pitch do.", funny: true } ],
    [ { text: "Simran ko bolo ki tum chhod do, main akela sambhal lunga",
        reaction: "Arnav, partner ko hataana solution nahi. Simran ke saath baith kar dono ideas discuss karo." },
      { text: "Kaun sahi hai iska faisla 'kaun pehle chai laata hai' se karo",
        reaction: "Arnav, chai se startup nahi chalta! Simran ke saath baith kar dono ideas ki baat karo.", funny: true } ],
    [ { text: "Customer ko discount coupon bhej do aur problem par kuch mat karo",
        reaction: "Arnav, coupon se problem theek nahi hoti. Maafi maango aur turant fix karo." },
      { text: "Customer ko 'Aapka feedback humein bahut pasand aaya' likh kar heart emoji bhejo",
        reaction: "Arnav, complaint par heart emoji bhejna mazak ban jaata hai. Maafi maango aur turant fix karo.", funny: true } ],
    [ { text: "Doosron ki raay pooch kar wahi kar do jo sab bolein",
        reaction: "Arnav, doosron ki raay sunna theek hai par decision risk analysis se lena chahiye. Dono options ka analysis karo." },
      { text: "Ganesh ji ki photo ke saamne sikka uchhaal kar decide karo",
        reaction: "Arnav, aashirwad achha hai par business risk analysis se chalta hai! Dono options ka risk analyse karo.", funny: true } ]
  ],
  cybersecurity: [
    [ { text: "Alert ko ignore kar do, shayad system ki galti hogi",
        reaction: "Devansh, alert ko ignore karna sabse badi galti hai. Login logs aur IP details carefully investigate karo." },
      { text: "Hacker ko ek email bhejo: 'Bhai, please login mat karo'",
        reaction: "Devansh, hacker email padh kar nahi rukta! Logs aur IP details investigate karo.", funny: true } ],
    [ { text: "Sabhi employees ko email karke bolo ki password badal do, aur breach ko chhod do",
        reaction: "Devansh, password badalna zaroori hai par pehle breach contain karo. Phir management ko jaankari do." },
      { text: "Server ki taar nikaal kar band kar do aur ghar chale jao",
        reaction: "Devansh, taar nikaal kar ghar nahi jaate! Breach ko controlled tareeke se contain karo aur management ko batao.", funny: true } ],
    [ { text: "Sirf IT team ko batao, baaki employees ko pareshan mat karo",
        reaction: "Devansh, fake email sabhi ko mila hai. Clear instructions ke saath sabko turant alert karo." },
      { text: "Sabhi ke inbox mein bade 'HACKER ALERT!' likh ke meme bhejo",
        reaction: "Devansh, meme se log hasenge, samjhenge nahi. Clear instructions ke saath sabko alert karo.", funny: true } ],
    [ { text: "Pehle ghar par so kar subah tak wait karo, sab thik ho jayega",
        reaction: "Devansh, cyber attack ka wait nahi hota. Critical systems ko pehle isolate karo." },
      { text: "Company ke sabhi computers par ek saath 'Ctrl+Alt+Delete' dabao",
        reaction: "Devansh, sab computers par ek saath Ctrl+Alt+Delete se attack nahi rukta! Critical systems ko isolate karo.", funny: true } ],
    [ { text: "Ek chhota email likh do ki 'Incident handle ho gaya' aur baat khatam",
        reaction: "Devansh, chhota email kaafi nahi. Detailed report banao aur security improve karne ka plan do." },
      { text: "Meeting mein sabko attack ki kahani ek horror movie ki tarah sunao",
        reaction: "Devansh, kahani mazedaar hai par report facts se banti hai. Detailed report aur improvement plan do.", funny: true } ]
  ],
  law: [
    [ { text: "Client ko bolo ki wo sirf ek line mein apni problem likh kar de",
        reaction: "Aryan, ek line mein case samajhna mushkil hai. Client se sabhi documents aur clear details maango." },
      { text: "Client ki kundli dekh kar case ka result batao",
        reaction: "Aryan, kundli se nahi, documents se case chalta hai! Sabhi documents aur clear details maango.", funny: true } ],
    [ { text: "Loophole ko use karo par judge ko poori baat mat batao",
        reaction: "Aryan, ye bhi sahi nahi. Ethical tareeke se strong arguments taiyaar karo." },
      { text: "Judge ko ek tasty mithai dikhakar arguments shuru karo",
        reaction: "Aryan, mithai se nahi, ethics se case jeeta jaata hai! Ethical arguments taiyaar karo.", funny: true } ],
    [ { text: "Judge se shikayat karo ki opposing lawyer bahut zor se bol raha hai",
        reaction: "Aryan, shikayat se argument nahi jeeta jaata. Shaant reh kar facts aur evidence ke saath jawab do." },
      { text: "Opposing lawyer se bhi zyada zor se chillakar apni awaaz badhao",
        reaction: "Aryan, awaaz badhane se argument mazboot nahi hota. Shaant reh kar facts aur evidence do.", funny: true } ],
    [ { text: "Sirf woh facts batao jo case ke liye achhe hain, baaki chhod do",
        reaction: "Aryan, aadha sach bhi sach chhupana hi hai. Client ko samjhao aur honestly case lado." },
      { text: "Client ko bolo ki agar wo chup rahe toh main use chai ki treat doonga",
        reaction: "Aryan, treat se sach nahi chhupta! Client ko samjhao ki honestly case ladna sahi hai.", funny: true } ],
    [ { text: "Result se pehle hi bhagwan se dua karke court chhod do",
        reaction: "Aryan, result ka saamna karna hi asli lawyer ki pehchaan hai. Result ko positively lo." },
      { text: "Judge ke saamne 'Objection!' chillao, chahe judgment aapke haq mein ho",
        reaction: "Aryan, judgment mein 'Objection!' nahi hota! Result ko positively lo aur jeet-haar se seekho.", funny: true } ]
  ],
  corporatelaw: [
    [ { text: "Contract ka sirf summary padhkar approve kar do",
        reaction: "Rohan, summary mein important clauses chhoot jaate hain. Poora contract line by line padho." },
      { text: "Contract ko ulta padh kar dekho, shayad koi naya meaning mile",
        reaction: "Rohan, ulta padhne se koi naya meaning nahi milta! Poora contract dhyan se line by line padho.", funny: true } ],
    [ { text: "Client ko seedha bata do, Kapoor Sir ko batane ki zaroorat nahi",
        reaction: "Rohan, senior ko pehle batana sahi process hai. Risky clause turant Kapoor Sir ko batao." },
      { text: "Risky clause par ek bada sa smiley bana do taaki wo risky na lage",
        reaction: "Rohan, smiley se risk kam nahi hota! Risky clause turant Kapoor Sir ko batao.", funny: true } ],
    [ { text: "Chaliye, aadha contract dekh lete hain aur baaki baad mein",
        reaction: "Rohan, aadha review aadhi suraksha hai. Client ko samjhao ki poora review zaroori hai." },
      { text: "Client ko coffee pilao taaki wo jaldi bhool jaye",
        reaction: "Rohan, coffee se jaldi nahi jaati! Client ko samjhao ki poora review zaroori hai.", funny: true } ],
    [ { text: "Table chhod kar bahar chale jao aur dhamki do ki deal cancel kar denge",
        reaction: "Rohan, dhamki se negotiation bigadta hai. Shaant rehke dono taraf ke fayde wali baat karo." },
      { text: "Negotiation ki jagah rock-paper-scissors se decide karo",
        reaction: "Rohan, rock-paper-scissors se contract nahi bante! Dono taraf ke fayde wali baat karo.", funny: true } ],
    [ { text: "Sign karwao aur baad mein dekh lenge ki kuch missing hai kya",
        reaction: "Rohan, sign hone ke baad kuch badalna bahut mushkil hai. Ek baar aur sabhi terms confirm karo." },
      { text: "Sign karne se pehle pen ko aashirwad do taaki galti na ho",
        reaction: "Rohan, pen ke aashirwad se nahi, terms ke review se galti rukti hai! Ek baar aur confirm karo.", funny: true } ]
  ],
  teaching: [
    [ { text: "Board par bada sa 'SILENCE' likh kar chup baith jao",
        reaction: "Anjali, board par likhne se class shaant nahi hoti. Shaant aawaz mein intro do aur dosti se baat karo." },
      { text: "Sabko bolo ki jo sabse zor se chillayega usse chocolate milegi",
        reaction: "Anjali, chocolate se shor badhta hai, kam nahi! Shaant aawaz mein intro do aur dosti se baat karo.", funny: true } ],
    [ { text: "Rohan ko doosre student se copy karne ko bol do",
        reaction: "Anjali, copy karne se concept nahi aata. Rohan ko break time mein alag se samjhao." },
      { text: "Rohan ko ek naya naam do - 'Genius Rohan' - aur bolo ki ab tumhe sab samajh aayega",
        reaction: "Anjali, naam se concept nahi aata! Rohan ko break time mein alag se samjhao.", funny: true } ],
    [ { text: "Ignore karo, bachche khud sulajh lenge",
        reaction: "Anjali, bullying ignore karne se badhti hai. Dono students se alag alag baat karke poori baat samjho." },
      { text: "Karan ko ek hafte tak sabki bench saaf karne ki saza do aur kuch mat poochho",
        reaction: "Anjali, bina poori baat sune saza dena sahi nahi. Dono students se alag baat karke samjho.", funny: true } ],
    [ { text: "Parent ko bolo ki unke bachche ki padhai mein unki hi galti hai",
        reaction: "Anjali, parent ko blame karne se baat bigadti hai. Shaant rehkar bachche ki progress aur sudhaar ke tareeke batao." },
      { text: "Parent ko marks ki jagah ek gulab ka phool do aur muskurao",
        reaction: "Anjali, phool achha hai par marks ki baat bhi zaroori hai! Shaant rehkar progress aur sudhaar ke tareeke batao.", funny: true } ],
    [ { text: "Unhe bol do ki agli baar bhi aisa hi hoga agar aise hi rahe",
        reaction: "Anjali, aise bolne se hausla toot jaata hai. Unhe encourage karo aur behtar karne ka plan banao." },
      { text: "Unhe bolo ki fail hone ka matlab hai 'First Attempt In Learning' aur party karwao",
        reaction: "Anjali, positive rehna achha hai par plan bhi zaroori hai. Unhe encourage karo aur saath mein behtar plan banao.", funny: true } ]
  ],
  college: [
    [ { text: "Sabhi phones ko table par jama kar lo aur lecture shuru karo",
        reaction: "Karan, zabardasti se engagement nahi aata. Interactive tareeke se lecture shuru karo." },
      { text: "Sabko bolo ki phone mein dekh lo ki mera lecture kaisa lag raha hai",
        reaction: "Karan, phone mein dekhne se lecture nahi sudharta! Interactive tareeke se lecture start karo.", funny: true } ],
    [ { text: "Student ko bolo ki tum pehle khud padho, phir sawaal karo",
        reaction: "Karan, sawaal poochhna seekhne ki nishani hai. Student ki baat sunno aur shaant rehke jawab do." },
      { text: "Student ko bolo ki tumhara sawaal itna mushkil hai ki mera chai ka time ho gaya",
        reaction: "Karan, chai ke bahane sawaal se bhaagna sahi nahi! Student ki baat sunno aur shaant rehke jawab do.", funny: true } ],
    [ { text: "Attendance zabardasti mandatory kar do aur late aane par marks kaat lo",
        reaction: "Karan, zabardasti se log class mein baithte hain par seekhte nahi. Practical examples aur activities add karo." },
      { text: "Har class ke baad ek free samosa ka announcement karo",
        reaction: "Karan, samosa se attendance badhegi par seekhna nahi! Practical examples aur activities add karo.", funny: true } ],
    [ { text: "Sabhi students ko ek saath punishment de do taaki koi cheating na kare",
        reaction: "Karan, sabko saza dena anyay hai. Fair tareeke se investigate karo aur dono taraf ki baat suno." },
      { text: "Cheating pakadne ke liye CCTV ki jagah ek jasoos ka costume pehen lo",
        reaction: "Karan, costume mazedaar hai par fair investigation ke liye kaam nahi aata! Dono taraf ki baat suno.", funny: true } ],
    [ { text: "Sirf top students ko congratulate karo, baaki ko ignore karo",
        reaction: "Karan, baaki students ko bhi guidance chahiye. Results analyse karke agle semester ka plan sudharo." },
      { text: "Results ka chart banao aur usse frame karke ghar mein tang do",
        reaction: "Karan, frame mein tangne se result nahi sudhrega! Results analyse karke agle semester ka plan sudharo.", funny: true } ]
  ],
  police: [
    [ { text: "Dono paksho ko bolo ki thane aa kar baat karein, yahan kuch nahi karunga",
        reaction: "Ishaan, mauke par hi shaanti se dono ki baat sunna zaroori hai. Shaant rehkar dono paksho ki baat suno." },
      { text: "Seeti bajakar sabko line mein khada karo jaise school ki assembly ho",
        reaction: "Ishaan, seeti se bheed control hoti hai par sunna zaroori hai! Shaant rehkar dono paksho ki baat suno.", funny: true } ],
    [ { text: "Dukaandar se bolo ki khud chor ko dhoondh le aur hum ko bata de",
        reaction: "Ishaan, investigation police ka kaam hai. Pehle CCTV footage aur evidence collect karo." },
      { text: "Kutte ko sungha kar bolo ki 'Ja chor ko dhoondh laa'",
        reaction: "Ishaan, kutte ka kaam alag hota hai aur evidence ka alag! Pehle CCTV aur evidence carefully collect karo.", funny: true } ],
    [ { text: "Dono ko thane le jao aur wahin case ke baare mein baat karo",
        reaction: "Ishaan, bina samjhe thane le jaana sahi nahi. Shaant rehkar victim ko support do aur sahi resource batao." },
      { text: "Dono ko ek saath pakoda khilao aur bolo ki ab lado mat",
        reaction: "Ishaan, pakode se jhagda nahi sulajhta! Shaant rehkar victim ko support do aur sahi resource batao.", funny: true } ],
    [ { text: "Bheed ko chillakar bolo ki koi bhi chor ko pakad le",
        reaction: "Ishaan, bheed ko order dene se nuksaan ho sakta hai. Bheed ko safe rakhte hue plan se peecha karo." },
      { text: "Chor ke peeche bhaagne ke bajay uska naam-pata poochh kar hi kaam chalao",
        reaction: "Ishaan, chor apna pata nahi batata! Bheed ko safe rakhte hue plan se peecha karo.", funny: true } ],
    [ { text: "Paisa le lo par bolo ki ye sirf ek 'gift' hai, isliye theek hai",
        reaction: "Ishaan, rishwat ko gift kehne se wo rishwat hi rehti hai. Paisa lene se saaf mana karo." },
      { text: "Paise ko ATM mein jamaa kar do aur bolo ki ye sab 'donation' hai",
        reaction: "Ishaan, rishwat ko donation bolne se kaam nahi chalta! Paisa lene se saaf mana karo aur imandari se kaam karo.", funny: true } ]
  ],
  detective: [
    [ { text: "Ek sabse mashhoor chor ki file nikal kar usi ko suspect maan lo",
        reaction: "Vivaan, bina evidence ke suspect banana kamzor investigation hai. Crime scene ko bariki se examine karo." },
      { text: "Crime scene mein magnifying glass leke Sherlock ki tarah 'Elementary!' bolo",
        reaction: "Vivaan, Sherlock banna achha hai par asli kaam evidence collect karna hai! Crime scene ko bariki se examine karo.", funny: true } ],
    [ { text: "Dono clues ko phenk do aur naye clue ka wait karo",
        reaction: "Vivaan, clues ko phenkna nahi, cross-check karna hai. Dono clues ko carefully verify karo." },
      { text: "Dono clues ka faisla sikke se karo ki kaun sahi hai",
        reaction: "Vivaan, sikke se nahi, evidence se suspect milta hai! Dono clues ko carefully cross-check karo.", funny: true } ],
    [ { text: "Suspect ko raat bhar bhookha rakh kar poochho",
        reaction: "Vivaan, aisa karna anyay hai aur evidence bekaar ho sakta hai. Shaant rehkar sawaal poocho aur dhyan se suno." },
      { text: "Suspect ko ek joke sunao aur agar wo hansa toh wahi chor hai",
        reaction: "Vivaan, hansi se chor nahi pakde jaate! Shaant rehkar sawaal poocho aur dhyan se suno.", funny: true } ],
    [ { text: "Naye clue ko ignore karo, purane clues par hi bharosa rakho",
        reaction: "Vivaan, naya clue case ka rukh badal sakta hai. Naye clue ko purane evidence ke saath cross-verify karo." },
      { text: "Naye clue ko seene se lagakar bolo 'Yahi asli hai!' aur case close karo",
        reaction: "Vivaan, seene se lagane se clue sahi nahi hota! Naye clue ko purane evidence ke saath cross-verify karo.", funny: true } ],
    [ { text: "Bas is jeet ka jashn manao aur agle case mein bhi wahi purana tareeka use karo",
        reaction: "Vivaan, jeet ke baad seekhna band nahi karna chahiye. Hamesha thorough aur fair investigation karo." },
      { text: "Asli chor ko ek medal do kyunki usne bahut mehnat se chori ki",
        reaction: "Vivaan, chor ko medal nahi, saza milti hai! Hamesha thorough aur fair investigation ka commitment rakho.", funny: true } ]
  ],
  government: [
    [ { text: "Line mein jo sabse buzurg hain unhi ki files pehle dekho, baaki ko kal aane bolo",
        reaction: "Meher, buzurg ki madad achhi baat hai par sabki files priority se dekhni chahiye. Systematically kaam karo." },
      { text: "Sabko token number ki jagah unke favourite fruit ka naam do",
        reaction: "Meher, fruit ke naam se line nahi chalti! Priority ke hisaab se files sort karo aur systematically kaam karo.", funny: true } ],
    [ { text: "Sirf apni file par ye shortcut try karo, kisi aur ko mat batana",
        reaction: "Meher, corruption chhupa kar bhi corruption hi rehta hai. Is scheme se saaf inkar karo." },
      { text: "Senior clerk ko bolo ki wo shortcut khud hi chhoti si dukan mein bech de",
        reaction: "Meher, corrupt scheme ka koi market nahi hona chahiye! Saaf inkar karo aur sahi tareeke se kaam karo.", funny: true } ],
    [ { text: "Kisan ko bolo ki kal aana, aaj mera mood theek nahi hai",
        reaction: "Meher, mood se nahi, zimmedari se kaam hota hai. Kisan ko shaant karke case ki sahi status samjhao." },
      { text: "Kisan ko chai aur biscuit dekar bolo ki case abhi chai jaisa garam hai",
        reaction: "Meher, chai achhi hai par case ki status batana zaroori hai! Kisan ko shaant karke sahi status samjhao.", funny: true } ],
    [ { text: "Pehle news channel se poochho ki kis gaon mein kitna paani bhara hai",
        reaction: "Meher, news se pehle apni team se ground report lo. Sabse zyada prabhavit gaon ko priority do." },
      { text: "Sabko naav ki tarah tairne ka training dena shuru kar do",
        reaction: "Meher, training baad mein! Sabse zyada prabhavit gaon ko pehle priority do aur relief team bhejo.", funny: true } ],
    [ { text: "Review mein sirf achhi baatein batao aur galtiyan chhupa lo",
        reaction: "Meher, apni galtiyan maan kar hi sudhar aata hai. Logon ki seva ko hamesha priority banaye rakho." },
      { text: "DM Sahab ko ek badi si 'Best Officer' ki trophy khud hi dekar dikhao",
        reaction: "Meher, trophy khud dene se seva nahi hoti! Logon ki seva ko hamesha priority banaye rakho.", funny: true } ]
  ],
  business: [
    [ { text: "Client ki history ko chhod do, bas ek achha sa smile lekar chale jao",
        reaction: "Naina, smile achhi hai par preparation bhi zaroori hai. Key numbers aur client history quickly revise karo." },
      { text: "Meeting mein lucky shirt pehen kar jao aur prepare mat karo",
        reaction: "Naina, shirt se nahi, preparation se deal hoti hai! Key numbers aur client history revise karo.", funny: true } ],
    [ { text: "Client ko bolo ki ye final price hai aur uske baad baat mat karo",
        reaction: "Naina, rigid hone se deal chhoot sakti hai. Value explain karo aur reasonable middle ground offer karo." },
      { text: "Client ko free chai ka combo offer karo aur price ko bhool jao",
        reaction: "Naina, chai ke combo se pricing solve nahi hoti! Value clearly explain karo aur middle ground offer karo.", funny: true } ],
    [ { text: "Team ko bolo ki agle month ka target bhi abhi le lo aur is month ko bhool jao",
        reaction: "Naina, purane target ko bhoolne se team ki growth nahi hoti. Team ke saath realistic extra-push plan banao." },
      { text: "Sabko bolo ki sales ka number likh kar ek lucky charm ghar mein tang lo",
        reaction: "Naina, charm se sales nahi badhti! Team ke saath mil kar realistic extra-push plan banao.", funny: true } ],
    [ { text: "Ye galti kisi doosre team member par daal do",
        reaction: "Naina, doosre par daalne se problem badhti hai. Ms. Malhotra ko turant sahi jaankari do." },
      { text: "Report ki ek naye colour mein nayi copy bhej do aur bolo ki ye 'updated design' hai",
        reaction: "Naina, colour badalne se galti nahi sudhrti! Ms. Malhotra ko turant sahi jaankari do.", funny: true } ],
    [ { text: "Slides ko ratt kar seedha padh do bina client ki taraf dekhe",
        reaction: "Naina, client se connect karna zaroori hai. Confidence ke saath apni strategy clearly present karo." },
      { text: "Presentation ko ek gaane ke roop mein gaa kar sunao",
        reaction: "Naina, gaana mast hai par client ko strategy samajhni hai! Confidence ke saath clearly present karo.", funny: true } ]
  ],
  pilot: [
    [ { text: "Carry the standard fuel and simply depend on air traffic control to guide the aircraft around the storm",
        reaction: "Aarav, ATC helps with routing but cannot create extra fuel for you. Extra contingency fuel is your own responsibility as the commander." },
      { text: "Load the extra fuel by asking the cabin crew to bring their own cans from the canteen",
        reaction: "Aarav, fuel goes in through the refuelling truck, not from the canteen! Request the extra contingency fuel and offload cargo to stay within limits.", funny: true } ],
    [ { text: "Ask ATC to tell you whether the area behind the cell is clear and follow their word alone",
        reaction: "Aarav, ATC radar often cannot see weather the way your onboard radar can. Confirm it yourself and take the wider deviation." },
      { text: "Turn the radar screen off, since if you cannot see the storm, it cannot see you",
        reaction: "Aarav, that logic works for hide-and-seek, not for thunderstorms! Keep the radar on and take a wide deviation.", funny: true } ],
    [ { text: "Switch off the autopilot and fly manually at full speed to fight the turbulence",
        reaction: "Aarav, flying faster in turbulence adds structural stress. Slow to turbulence penetration speed and hold a steady attitude." },
      { text: "Announce on the PA that passengers should hold hands and sing to keep the aircraft steady",
        reaction: "Aarav, a sing-along is cute, but the aircraft needs correct speed and attitude! Slow to the turbulence penetration speed and inform ATC.", funny: true } ],
    [ { text: "Ask the cabin crew to check whether passengers would prefer to wait or divert",
        reaction: "Aarav, fuel decisions belong to the commander, not a passenger vote. Divert now while the fuel margin is still comfortable." },
      { text: "Cut the engine power for a few minutes to save fuel while holding",
        reaction: "Aarav, shutting down power in the air is not a fuel-saving trick! Divert to the alternate with comfortable reserve.", funny: true } ],
    [ { text: "Land immediately at a much higher approach speed to stay safe from the crosswind",
        reaction: "Aarav, a much higher speed cuts your stopping margin and does not cure wind shear. Keep the approach stable and be ready for a go-around." },
      { text: "Ask the passengers to lean to one side to balance the crosswind",
        reaction: "Aarav, passengers leaning to one side will not fix a crosswind! Fly the stable approach with the go-around briefed.", funny: true } ]
  ],
  airforce: [
    [ { text: "Load gear for maximum capacity and reduce fuel only after seeing how the engine performs at altitude",
        reaction: "Dhruv, discovering your limit in mid-air can be fatal at 14,000 feet. Calculate the limit before takeoff from the density-altitude chart." },
      { text: "Ask the rescue team to fold their gear into origami to make it lighter",
        reaction: "Dhruv, origami is impressive but weight is weight! Calculate the real limit from the chart and trim gear and fuel.", funny: true } ],
    [ { text: "Take the leeward route but fly slower to be extra careful",
        reaction: "Dhruv, slowing down on the leeward side does not remove the downdrafts. Take the windward route despite the extra time." },
      { text: "Hum loudly and hope the wind gets scared of the helicopter",
        reaction: "Dhruv, the wind is not scared of anyone! Take the longer windward route and avoid the rotor turbulence.", funny: true } ],
    [ { text: "Hover as normal but tell the crew to hold on tightly in case power runs short",
        reaction: "Dhruv, holding on tightly is not a power plan. Recheck the power margin and use a one-skid touch if it is tight." },
      { text: "Land the helicopter fully on the ledge and hope the rocks do not mind",
        reaction: "Dhruv, a narrow rocky ledge cannot take a full landing! Recheck the margin and use a one-skid touch if power is tight.", funny: true } ],
    [ { text: "Take three survivors on the first lift, slightly above the safe limit, and return quickly for the rest",
        reaction: "Dhruv, even a small overload cuts your power margin at this altitude. Stick to two per trip and plan a second lift." },
      { text: "Ask the survivors to breathe in and become lighter for the flight",
        reaction: "Dhruv, breathing in does not change weight! Stick to the calculated payload and plan a second lift.", funny: true } ],
    [ { text: "Stay silent and fly through the valley without reporting until radio contact returns",
        reaction: "Dhruv, silence is risky - base needs your position. Follow the briefed track and report at each checkpoint." },
      { text: "Shout your position out of the window and hope base can hear you",
        reaction: "Dhruv, base is far too far to hear you! Stay on the briefed safe track and report at each planned checkpoint.", funny: true } ]
  ],
  defence: [
    [ { text: "Ask local villagers whether they think the road edge will hold and go with their opinion",
        reaction: "Yuvraj, local knowledge helps but stability must be tested. Send a light reconnaissance vehicle across first." },
      { text: "Throw a pebble at the road edge and wait for it to say 'ouch'",
        reaction: "Yuvraj, roads do not talk! Send a light reconnaissance vehicle across first to test the edge.", funny: true } ],
    [ { text: "Use the floodlights for only the first hour, then switch off and continue in complete darkness",
        reaction: "Yuvraj, working blind is dangerous and floodlights break blackout discipline. Use shielded low lighting at a careful pace." },
      { text: "Ask the soldiers to bring torches shaped like fireflies to blend in",
        reaction: "Yuvraj, fireflies would be lovely but they are not a plan! Use shielded low lighting and respect blackout discipline.", funny: true } ],
    [ { text: "Send half of the convoy across together and the rest after a short break",
        reaction: "Yuvraj, half the convoy still loads the repair heavily at once. Cross one vehicle at a time with spacing." },
      { text: "Ask the engineers to sign the road with their names so it feels responsible",
        reaction: "Yuvraj, signatures do not add strength! Cross one vehicle at a time and watch the surface for movement.", funny: true } ],
    [ { text: "Split the load half and half so both fuel and medicine go on the first crossing, even slightly over the weight limit",
        reaction: "Yuvraj, exceeding the limit risks the whole crossing. Prioritise medical and emergency supplies first, fuel next." },
      { text: "Send the fuel gift-wrapped so that it weighs less",
        reaction: "Yuvraj, gift wrap adds weight, not lightness! Prioritise medical supplies on the first crossing.", funny: true } ],
    [ { text: "Submit a short verbal update instead of a written report and say everything went fine",
        reaction: "Yuvraj, 'everything went fine' is not honest and leaves the road unfixed. File a detailed, honest report." },
      { text: "Write the report as a poem about snowflakes so no one notices the risky parts",
        reaction: "Yuvraj, lovely poem, but hiding risk in verse helps no one! File a detailed, honest report on the road's condition.", funny: true } ]
  ],
  atc: [
    [ { text: "Tell 412 over the radio to hurry up and let 908 continue, trusting the crew to speed up",
        reaction: "Meera, rushing a crew that is running checklists creates errors, and the runway still won't be clear. Send 908 around if it will not be clear in time." },
      { text: "Wave a big flag from the tower window to make 412 go faster",
        reaction: "Meera, they can't see your flag from the runway, and the tower window is not a signalling station! Tell 412 to hold or vacate and send 908 around.", funny: true } ],
    [ { text: "Ask both pilots what they can see and decide together who should move",
        reaction: "Meera, that wastes precious minutes. Give clear, standard instructions and traffic information right away." },
      { text: "Switch off the radar alert sound so it stops annoying the room",
        reaction: "Meera, silencing the alarm does not silence the conflict! Give one aircraft a clear turn and the other a level change.", funny: true } ],
    [ { text: "Ask the Mayday aircraft to join the queue at position two so the others are not delayed too much",
        reaction: "Meera, an emergency aircraft goes first, not second. Give it priority and alert emergency services." },
      { text: "Tell the Mayday pilot to flap the wings gently to save fuel",
        reaction: "Meera, aircraft are not birds, and flapping doesn't save fuel! Give priority, clear the way and alert the fire service.", funny: true } ]
  ],
  navy: [
    [ { text: "Turn off the radar to avoid attracting attention and wait quietly until the contact passes",
        reaction: "Rohan, turning off your eyes is the worst possible move. Keep tracking, hail it and report to the Commander." },
      { text: "Wave a torch at the contact and shout 'Hello, friend or foe?'",
        reaction: "Rohan, shouting across the sea won't be heard and tells you nothing! Track it on radar, hail it on the radio and report.", funny: true } ],
    [ { text: "Ask the chief engineer to pour cold water on the engine and keep going at full speed",
        reaction: "Rohan, cold water on a hot engine can crack it. Reduce speed, switch to the standby engine and report the delay." },
      { text: "Ask the crew to row the ship for the last stretch to give the engine a break",
        reaction: "Rohan, a warship being rowed? Great picture, terrible plan! Reduce speed, switch to the standby engine and report.", funny: true } ],
    [ { text: "Send only a radio message telling the boat to wait until the weather clears",
        reaction: "Rohan, seven lives are in immediate danger. Inform headquarters, approach safely and assess the sea state for a rescue." },
      { text: "Throw a life jacket from the ship and hope it lands on the boat a kilometre away",
        reaction: "Rohan, the arm is strong but not that strong! Proceed at safe speed and launch the rescue boat when conditions allow.", funny: true } ]
  ],
  datascience: [
    [ { text: "Report the 40 percent but add a small note that it may be a little high",
        reaction: "Ananya, a footnote won't undo a wrong headline number. Check for duplicates and join errors first." },
      { text: "Send the CEO a thank-you card for the amazing 40 percent and ask for a raise",
        reaction: "Ananya, a raise request based on unverified data is a risky bet! Check for duplicates first, then report the verified number.", funny: true } ],
    [ { text: "Show the full chart but make the line thick and colourful so it looks positive",
        reaction: "Ananya, styling to hide a decline is still misleading. Show it honestly with context and next steps." },
      { text: "Draw a big happy smiley over the dip so nobody worries",
        reaction: "Ananya, smileys are lovely but they do not fix declines! Show the full honest chart with reasons and next steps.", funny: true } ],
    [ { text: "Trust the accuracy for now and check precision and recall next month",
        reaction: "Ananya, deploying first and checking later costs real customers. Measure precision and recall before using it." },
      { text: "Rename the model 'Super Accurate AI' so it feels trustworthy",
        reaction: "Ananya, a new name doesn't change the metrics! Measure precision and recall and rebalance the data.", funny: true } ]
  ],
  appdev: [
    [ { text: "Add dark mode tonight but tell the team tomorrow, after launch",
        reaction: "Neel, telling the team after launch is too late to manage the risk. Explain it now and ship dark mode in the next update." },
      { text: "Make the whole app dark by setting the phone brightness to zero",
        reaction: "Neel, that's not dark mode, that's a black screen! Explain the risk and plan dark mode for the next update.", funny: true } ],
    [ { text: "Tell users of older phones to buy new phones before using the app",
        reaction: "Neel, users won't upgrade just for our app. Fix the crash or use a staged rollout that excludes the affected phones." },
      { text: "Add a pop-up saying 'Please throw away your old phone'",
        reaction: "Neel, that's the fastest way to earn one-star reviews! Fix the crash or use a staged rollout.", funny: true } ],
    [ { text: "Ask users on social media to describe exactly what is slow and wait for their replies",
        reaction: "Neel, user replies help, but the logs already hold the facts. Check crash and performance logs and analytics first." },
      { text: "Blame the users' internet in your reply to every review",
        reaction: "Neel, blaming users won't fix anything! Check logs and analytics to find which screens and devices are slow.", funny: true } ]
  ],
  athlete: [
    [ { text: "Watch the other runners' shoulders and move when they do",
        reaction: "Aditya, copying others makes you late or disqualified. Listen for the gun and react to it." },
      { text: "Shout 'Bang!' yourself and start running",
        reaction: "Aditya, the starter's pistol is the only 'bang' that counts! React to the gun instead of creating your own.", funny: true } ],
    [ { text: "Tell only Sana and ask her to keep it a secret",
        reaction: "Aditya, a secret injury is still a hidden injury. Tell the coach and physio so they can plan safe treatment." },
      { text: "Rub a lot of chilli oil on the leg because it makes everything feel better",
        reaction: "Aditya, chilli oil is for food, not for muscles! Tell the coach and physio exactly what happened.", funny: true } ],
    [ { text: "Skip the plan and simply run as fast as you can from the gun",
        reaction: "Aditya, in a 400, going all-out from the start leaves nothing for the home straight. Stick to the race plan." },
      { text: "Run the first lap backwards to confuse lane five",
        reaction: "Aditya, running backwards will confuse only you! Stay relaxed on the bend and attack in the last 100 metres.", funny: true } ]
  ],
  tennis: [
    [ { text: "Switch to an underarm serve for the rest of the match",
        reaction: "Ishaan, an underarm serve gives the point away easily. Reset the toss and use a safe second serve with spin." },
      { text: "Blame the ball, the racket and the weather in a long speech before serving",
        reaction: "Ishaan, the speech is longer than the rally! Slow down, reset your toss and serve with spin and margin.", funny: true } ],
    [ { text: "Play the next point badly on purpose to show the umpire his mistake",
        reaction: "Ishaan, throwing away points only helps your opponent. Ask politely for a check or use the review, then refocus." },
      { text: "Give the line judge your spare glasses as a friendly gift",
        reaction: "Ishaan, kind, but it won't change the call! Politely ask for a review, then refocus on the next point.", funny: true } ],
    [ { text: "Serve only to the opponent's forehand because it is your favourite side",
        reaction: "Ishaan, your favourite is not his weakness. Target his weaker backhand with deep, solid balls." },
      { text: "Hit every ball into the sky so the opponent gets confused looking up",
        reaction: "Ishaan, he won't be confused, just happy to collect free points! Play percentage tennis and target the weaker backhand.", funny: true } ]
  ],
  surgeon: [
    [ { text: "Read out only the patient's name and the procedure and skip the rest since the case is routine",
        reaction: "Nikhil, allergy and site checks are exactly what 'routine' cases hide. Complete the full checklist." },
      { text: "Ask the patient to double-check the checklist after waking up",
        reaction: "Nikhil, the patient is asleep and can't help! Complete the full safety checklist out loud before the first cut.", funny: true } ],
    [ { text: "Ask Nurse Latha to take over while you step away to check your notes",
        reaction: "Nikhil, stepping away in the middle of a bleed is dangerous. Announce the problem, control the bleeding and get help." },
      { text: "Sing a soothing song to the artery so it calms down",
        reaction: "Nikhil, arteries don't enjoy music! Announce the problem, apply pressure and ask for suction and help.", funny: true } ],
    [ { text: "Send the nurse to tell the family and stay in the operating room to avoid emotional moments",
        reaction: "Nikhil, the surgeon should face the family. Explain the complication in simple words yourself." },
      { text: "Give the family a medical journal with all the difficult terms and leave",
        reaction: "Nikhil, a journal is not an explanation! Speak in simple words and answer their questions honestly.", funny: true } ]
  ],
  pharmacist: [
    [ { text: "Dispense the smaller dose so that it is safe either way",
        reaction: "Aisha, an unclear dose can still be wrong at a lower level. Call the doctor to confirm before dispensing." },
      { text: "Ask the customer to read the doctor's handwriting for you",
        reaction: "Aisha, the customer is not a handwriting expert! Call the doctor to confirm the dose and the medicine.", funny: true } ],
    [ { text: "Sell just half a strip to keep it 'safe'",
        reaction: "Aisha, half a course is worse - it builds resistance. Explain kindly that antibiotics need a prescription." },
      { text: "Sell him a mango juice and tell him it is a natural antibiotic",
        reaction: "Aisha, mango juice is tasty but not an antibiotic! Explain kindly and suggest seeing a doctor.", funny: true } ],
    [ { text: "Give a smaller number of tablets so the interaction is less risky",
        reaction: "Aisha, fewer tablets do not remove the interaction. Explain the risk and check with her doctor." },
      { text: "Suggest that she wears a knee-warmer made of gold for the pain",
        reaction: "Aisha, gold won't cure knee pain! Explain the interaction risk and ask her to check with her doctor.", funny: true } ]
  ],
  judge: [
    [ { text: "Reject the adjournment immediately without hearing the advocate at all",
        reaction: "Vidya, refusing without hearing can be unfair. Ask for proof and allow a short final date with costs." },
      { text: "Grant the adjournment on condition that the advocate brings tea for the whole court",
        reaction: "Vidya, tea is welcome but justice can't be bought with it! Ask for proof and allow a short final date with a warning.", funny: true } ],
    [ { text: "Listen for two minutes but promise yourself not to be influenced",
        reaction: "Vidya, even two minutes of a one-sided chat damages trust. Ask him to argue openly with the other side present." },
      { text: "Reply by whispering 'The court is listening' and pointing at the ceiling",
        reaction: "Vidya, dramatic, but simply refuse! Ask him to make his points in open court.", funny: true } ],
    [ { text: "Postpone the verdict again so the noise dies down",
        reaction: "Vidya, delay doesn't remove pressure and hurts everyone waiting. Decide on evidence and law and explain the reasoning." },
      { text: "Ask the crowd outside to vote with a show of hands",
        reaction: "Vidya, courts are not talent shows! Decide only on the evidence and the law and explain your reasoning.", funny: true } ]
  ],
  legalaid: [
    [ { text: "Tell him to come back with a lawyer's fee and a proper contract",
        reaction: "Farhan, that misses the whole point of legal aid. Listen fully, explain his rights and collect the documents." },
      { text: "Promise to win his case and also arrange a free shop for him",
        reaction: "Farhan, great heart but wildly unrealistic! Explain his rights honestly and list the real next steps.", funny: true } ],
    [ { text: "Tell him half is better than nothing and ask him to sign right now",
        reaction: "Farhan, pushing him to sign is deciding for him. Explain the pros and cons and let him choose." },
      { text: "Flip a coin in front of him to make the decision",
        reaction: "Farhan, coins are for cricket, not for a family's wages! Explain everything and let Ramesh decide.", funny: true } ],
    [ { text: "Take the envelope but promise yourself to fight the case honestly anyway",
        reaction: "Farhan, taking it already compromises you. Refuse firmly, walk away and report it." },
      { text: "Ask if the envelope comes with a free samosa too",
        reaction: "Farhan, this is no joke to be haggled over! Refuse firmly, walk away and report it.", funny: true } ]
  ],
  cyberlaw: [
    [ { text: "Ask her to reply angrily to the account so they stop",
        reaction: "Rhea, angry replies can escalate things and clutter the evidence. Save the evidence and report it first." },
      { text: "Tell her to switch off the internet forever",
        reaction: "Rhea, that isn't a solution and she loses her whole online life! Save the evidence with links and timestamps, then file a complaint.", funny: true } ],
    [ { text: "Ask a rival platform to host her side of the story",
        reaction: "Rhea, that is not a legal route. Send a formal takedown notice with exact links." },
      { text: "Post 'Please delete this' 500 times in the comments",
        reaction: "Rhea, spamming comments won't create a legal duty! Send a formal takedown notice listing links and grounds.", funny: true } ],
    [ { text: "Submit the screenshots with a self-written note saying they are genuine",
        reaction: "Rhea, a note from you doesn't make evidence reliable. Get a forensic copy, a hash and the required certificate." },
      { text: "Bring the phone into court and ask the judge to scroll through it",
        reaction: "Rhea, that isn't how electronic evidence is proven! Prepare a forensic copy with a hash and a proper certificate.", funny: true } ]
  ],
  specialedu: [
    [ { text: "Give him extra reading homework so he practises more at home",
        reaction: "Mansi, more of the same struggle at home adds stress. Give him extra time and multi-sensory methods in a safe setting." },
      { text: "Let him read only when the wall clock is looking away",
        reaction: "Mansi, the clock isn't the problem, his comfort is! Skip public reading and use multi-sensory teaching.", funny: true } ],
    [ { text: "Suggest that she moves him to a stricter school",
        reaction: "Mansi, that sends the wrong message. Share your observations and his strengths kindly and suggest strategies." },
      { text: "Give her a report card written entirely in emojis",
        reaction: "Mansi, emojis won't help her understand! Share specific examples and practical strategies kindly.", funny: true } ],
    [ { text: "Tell the family to apply for accommodations after the results come out",
        reaction: "Mansi, after the results is too late. Prepare the report and formal application well before the deadline." },
      { text: "Ask the exam supervisor to read Aarush's mind",
        reaction: "Mansi, mind-reading is not on the approved list! File the formal application in advance.", funny: true } ]
  ],
  principal: [
    [ { text: "Call the boys' parents and tell them to punish their children at home",
        reaction: "Sunil, that skips a fair inquiry. Hear all sides, involve the counsellor and set clear consequences." },
      { text: "Make everyone listen to a friendship song on loop until they hug it out",
        reaction: "Sunil, the loop won't fix bullying! Inquire fairly, involve the counsellor and follow up.", funny: true } ],
    [ { text: "Tell him you will look into the marks and keep him waiting for a few weeks",
        reaction: "Sunil, false hope is just dishonesty in slow motion. Refuse politely and offer the formal re-evaluation." },
      { text: "Offer him the school canteen contract in exchange for peace",
        reaction: "Sunil, that is a bribe going both ways! Refuse politely and explain the re-evaluation process.", funny: true } ],
    [ { text: "Split the money in half and do both jobs badly",
        reaction: "Sunil, half of a safety fix is still a hazard. Fix the railing first and plan the smart board next." },
      { text: "Paint the loose railing in bright colours so nobody notices",
        reaction: "Sunil, a painted broken railing is still broken! Fix the unsafe railing first.", funny: true } ]
  ],
  coachmentor: [
    [ { text: "Tell Simran to catch up on her own and skip the next class if she is lost",
        reaction: "Rajat, skipping makes the gap bigger. Find the missing concepts and run a short doubt session." },
      { text: "Ask the toppers to shout the answers so she learns through the noise",
        reaction: "Rajat, shouting isn't teaching! Diagnose her gaps and give her a simple catch-up plan.", funny: true } ],
    [ { text: "Tell her to stop worrying and switch off from studies completely for the whole week",
        reaction: "Rajat, a total stop before the exam is not a balanced plan either. Listen, plan realistic study and rest, and involve the counsellor." },
      { text: "Prescribe her one plate of pakoras every hour for stress",
        reaction: "Rajat, pakoras are yummy but not a study plan! Listen kindly and help her make a realistic plan.", funny: true } ],
    [ { text: "Change the banner to '95% selection' as a safer exaggeration",
        reaction: "Rajat, a smaller lie is still a lie. Advertise honest, verifiable results." },
      { text: "Print 'Guaranteed Rank 1 or Free Samosa' on the banner",
        reaction: "Rajat, no coaching centre can guarantee that! Refuse misleading claims and use real results.", funny: true } ]
  ],
  cybercell: [
    [ { text: "Give him the helpline number and ask him to call the bank himself the next morning",
        reaction: "Jai, mornings are too late in fraud cases. Report immediately through the helpline and portal so the money can be frozen." },
      { text: "Tell him to call the scammer back and politely ask for the money",
        reaction: "Jai, the scammer is not a bank! Report to the fraud helpline immediately so the bank can freeze the money.", funny: true } ],
    [ { text: "Guess the account holder's password and log in to see the transactions",
        reaction: "Jai, that's illegal access. Send a formal request to the bank." },
      { text: "Ask the account holder to invite you for tea and chat about the money",
        reaction: "Jai, a chai chat isn't legal process! Send a formal request to the bank for the records.", funny: true } ],
    [ { text: "Switch the phone off completely and put it in your pocket",
        reaction: "Jai, pocketing it without sealing ruins the chain of custody. Isolate, seal, label and send it to the lab." },
      { text: "Change the phone wallpaper to an official police logo",
        reaction: "Jai, any change alters the evidence! Seal and label the device and let the forensic lab make a verified copy.", funny: true } ]
  ],
  forensic: [
    [ { text: "Photograph only the important items and pick up the rest to speed things up",
        reaction: "Ira, any item may matter. Photograph and document everything in place, then package each item separately." },
      { text: "Brush every surface in the house with glitter to find fingerprints",
        reaction: "Ira, glitter would ruin the scene! Wear protective gear and document everything before collecting.", funny: true } ],
    [ { text: "Tell the inspector it is 'probably' a match and leave out the smudge problem",
        reaction: "Ira, hiding the limits is overstating in disguise. Report the real findings with their limits." },
      { text: "Compare fingerprints by asking the suspect to give you a high-five",
        reaction: "Ira, a high-five isn't a forensic method! Report the actual findings with their limits.", funny: true } ],
    [ { text: "Move the sample to a new bag and start a fresh record from now",
        reaction: "Ira, that hides the earlier gap. Document the gap honestly and report it to the lab head." },
      { text: "Blame the missing entry on a ghost in the evidence room",
        reaction: "Ira, ghosts don't sign forms! Document the gap honestly and report it.", funny: true } ]
  ],
  nightbeat: [
    [ { text: "Shout loudly at the shop and hope whoever is inside runs out",
        reaction: "Karan, shouting alerts them to escape or fight. Stay outside, call control and cover the exits." },
      { text: "Knock on the shutter and ask 'Sir, are you a burglar?'",
        reaction: "Karan, burglars rarely answer honestly! Stay outside, inform control and wait for backup.", funny: true } ],
    [ { text: "Ask the child to walk home alone since she may remember the way",
        reaction: "Karan, a five-year-old alone at night is unsafe. Comfort her and inform control." },
      { text: "Give her a police cap and make her the officer of the night",
        reaction: "Karan, cute idea, but her safety comes first! Keep her safe, inform control and check missing-child reports.", funny: true } ],
    [ { text: "Stand back and film the argument on your phone",
        reaction: "Karan, watching doesn't keep anyone safe. Call backup, stay calm and separate the groups." },
      { text: "Blow the whistle continuously until everyone gets tired",
        reaction: "Karan, the whistle will only give everyone a headache! Separate the groups calmly and listen to each side.", funny: true } ]
  ],
  railways: [
    [ { text: "Let the train pass at low speed while the driver watches carefully",
        reaction: "Vishal, low speed doesn't replace authority when a signal has failed. Stop the train and follow the failure procedure." },
      { text: "Wave a red umbrella from the platform and hope the driver understands",
        reaction: "Vishal, umbrellas aren't signals! Stop the train and follow the written failure procedure.", funny: true } ],
    [ { text: "Let everyone enter and close the gates only after the train arrives",
        reaction: "Vishal, by then it is too late. Control entry early, announce, deploy staff and use barricades." },
      { text: "Announce free tea on Platform 2 to move the crowd",
        reaction: "Vishal, that might cause an even bigger stampede! Use clear announcements, staff and controlled entry.", funny: true } ],
    [ { text: "Hold the train for just two minutes and hope nobody notices",
        reaction: "Vishal, two minutes is still a rule broken. Politely refuse and offer the next available train." },
      { text: "Suggest the VIP's relatives ride on the engine to save time",
        reaction: "Vishal, passengers on the engine is a safety disaster! Politely refuse and offer help with the next train.", funny: true } ]
  ],
  forestofficer: [
    [ { text: "Ignore the cutting, since the villagers are poor and it is only firewood",
        reaction: "Arya, ignoring it lets the forest disappear. Stop the cutting and offer real alternatives with the village." },
      { text: "Give every villager a free axe so they only cut the trees they like",
        reaction: "Arya, that is the opposite of protection! Explain the law and work on alternatives.", funny: true } ],
    [ { text: "Chase the elephant with your jeep to hurry it back into the forest",
        reaction: "Arya, chasing panics it and can cause injuries. Move the crowd back and guide it gently." },
      { text: "Play loud film music so the elephant dances back home",
        reaction: "Arya, the elephant is not a music fan! Keep people back and bring the rapid response team.", funny: true } ],
    [ { text: "Call the villager to the office in front of everyone to give the details",
        reaction: "Arya, that exposes him. Verify the tip, plan the operation and keep the informant confidential." },
      { text: "Pin the tip on the village notice board asking loggers to stop politely",
        reaction: "Arya, the loggers will thank you and then escape! Verify the tip and plan a backed-up operation.", funny: true } ]
  ],
  taxofficer: [
    [ { text: "Call the trader in for a verbal warning without any written notice",
        reaction: "Meenal, a verbal warning is not due process. Issue a proper notice and give a fair chance to reply." },
      { text: "Judge his income by checking the brand of his shoes",
        reaction: "Meenal, shoes are not evidence! Issue a notice and decide based on documents.", funny: true } ],
    [ { text: "Accept the gift but promise yourself to decide the case fairly anyway",
        reaction: "Meenal, accepting it already compromises the case. Refuse firmly and report it." },
      { text: "Ask whether the gift box comes with a receipt for tax purposes",
        reaction: "Meenal, funny, but you must refuse and report! A gift in a pending case is a bribe attempt.", funny: true } ],
    [ { text: "Ignore the mistake completely to avoid extra work",
        reaction: "Meenal, ignoring the error is not fair to others. Allow correction and collect the tax due with interest." },
      { text: "Send him a bouquet with the penalty notice attached",
        reaction: "Meenal, a bouquet doesn't change the law! Let him correct the return and apply penalties only as justified.", funny: true } ]
  ],
  customs: [
    [ { text: "Search everyone whose bag looks big without asking any question",
        reaction: "Dev, size alone is not a risk indicator. Use risk indicators and search politely with a witness." },
      { text: "Ask him if he is carrying anything suspicious and trust whatever he says",
        reaction: "Dev, smugglers rarely confess! Use risk indicators, a polite search and a witness.", funny: true } ],
    [ { text: "Seize the gold but skip the receipt to save paperwork",
        reaction: "Dev, no receipt means no proof. Seize under a proper record with witnesses and a receipt." },
      { text: "Ask him whether he has more gold to donate to the department",
        reaction: "Dev, the department doesn't run on donations! Refuse the bribe and seize the gold properly.", funny: true } ],
    [ { text: "Allow all the medicines without checking any prescription",
        reaction: "Dev, that's a loophole smugglers love. Verify the prescription and the rules first." },
      { text: "Ask him to swallow a tablet to prove it is real medicine",
        reaction: "Dev, that's neither safe nor legal! Verify the prescription and apply the rules.", funny: true } ]
  ],
  finance: [
    [ { text: "Write 'Buy' but mention the debt in a very small note at the end",
        reaction: "Rahul, burying the risk is still misleading. Present the valuation and debt risks clearly." },
      { text: "Ask the stock's price chart to blink twice if it is overvalued",
        reaction: "Rahul, charts don't blink! Present the honest analysis with the risks stated clearly.", funny: true } ],
    [ { text: "Invest only a small amount so it isn't 'serious' insider trading",
        reaction: "Rahul, the size doesn't change the offence. Refuse the tip and inform compliance." },
      { text: "Ask your friend for tomorrow's newspaper instead",
        reaction: "Rahul, comedy aside, it is still an illegal tip! Refuse it and tell compliance.", funny: true } ],
    [ { text: "Ask him to wait a month and promise to check again then",
        reaction: "Rahul, saying nothing meaningful won't calm him. Listen, explain and review his goals and risk level." },
      { text: "Offer him a stress ball and a large bag of chips",
        reaction: "Rahul, snacks won't fix a portfolio worry! Listen, explain calmly and review his goals.", funny: true } ]
  ],
  ca: [
    [ { text: "Adjust only a small amount so the difference is hard to notice",
        reaction: "Ritika, small fraud is still fraud. Refuse to alter the accounts and suggest legitimate options." },
      { text: "Tell him to write a poem in the balance sheet to impress the bank",
        reaction: "Ritika, banks love numbers, not poems! Refuse and suggest a proper business plan.", funny: true } ],
    [ { text: "Ask the manager to recount the cash and adjust the books if it still doesn't match",
        reaction: "Ritika, recounting is fine, but hiding a mismatch is not. Investigate, document and report it." },
      { text: "Blame the cashier's pet parrot for taking the notes",
        reaction: "Ritika, parrots don't handle cash! Investigate the difference and document the findings.", funny: true } ],
    [ { text: "File a blank return now and add the details next week",
        reaction: "Ritika, a blank return is not a valid filing. File with the supportable figures and revise later." },
      { text: "Request the tax department to move the deadline to Diwali",
        reaction: "Ritika, the deadline won't move for festivals! File with supportable figures and revise later.", funny: true } ]
  ],
  marketing: [
    [ { text: "Target everyone so nobody feels left out",
        reaction: "Ishika, targeting everyone reaches nobody well. Use the research and test on a small scale." },
      { text: "Ask the office cat which audience it prefers",
        reaction: "Ishika, the cat is unbiased but unreliable! Use the survey data and test small first.", funny: true } ],
    [ { text: "Blame a junior team member publicly for the post",
        reaction: "Ishika, blaming individuals won't rebuild trust. Apologise sincerely and fix the approval process." },
      { text: "Reply to every angry comment with cat memes",
        reaction: "Ishika, memes won't calm a genuine complaint! Pause, apologise and explain what will change.", funny: true } ],
    [ { text: "Stop all marketing for the rest of the month to save the money",
        reaction: "Ishika, stopping everything kills momentum. Cut the weakest channels and protect the best." },
      { text: "Advertise by shouting the brand name from the office rooftop",
        reaction: "Ishika, brave, but not measurable! Analyse each channel's return and cut the weakest ones.", funny: true } ]
  ],
  hr: [
    [ { text: "Toss a coin between the two candidates",
        reaction: "Nandini, a coin isn't a fair hiring method. Use structured criteria and documented scores." },
      { text: "Hire the candidate who can juggle three oranges",
        reaction: "Nandini, juggling is fun but it's not a job criterion! Use structured criteria and select on merit.", funny: true } ],
    [ { text: "Ask the manager informally to be a bit nicer and leave it there",
        reaction: "Nandini, informal nudges skip the process. Follow the formal complaint process and protect Arun." },
      { text: "Give Arun a stress ball and a motivational poster",
        reaction: "Nandini, posters don't stop harassment! Follow the formal process with confidentiality.", funny: true } ],
    [ { text: "Announce it on a notice board on Friday evening and leave for the weekend",
        reaction: "Nandini, that is disrespectful. Tell each person privately with proper notice and support." },
      { text: "Send everyone a friendly balloon with the news inside",
        reaction: "Nandini, balloons and layoffs don't mix! Tell each person privately, with respect and support.", funny: true } ]
  ]
};

// Hindi + English text for the extra choices of the "doctor" story (episodes 1-5)
const extraTranslations = {
  doctor: [
    [ { text: { hindi: "मरीज़ को पहले दर्द की दवा दे दो और बाकी टेस्ट बाद में करेंगे", english: "Give the patient a painkiller first and do the other tests later" },
        reaction: { hindi: "रिया, बिना टेस्ट के सिर्फ़ दर्द की दवा देना सीने के दर्द में ख़तरनाक हो सकता है। पहले ECG और वाइटल्स।", english: "Riya, giving only a painkiller without tests can be dangerous in chest pain. ECG and vitals first." } },
      { text: { hindi: "मरीज़ से कहो 'आप गहरी साँस लो, मैं YouTube पर देख लेती हूँ क्या करना है'", english: "Tell the patient 'Just take deep breaths, I'll check YouTube for what to do'" },
        reaction: { hindi: "रिया, YouTube पर सब कुछ मिलता है, पर ER में नहीं! मरीज़ की जान का सवाल है - पहले ECG और वाइटल्स चेक करो।", english: "Riya, YouTube has everything, but not in the ER! A life is at stake - check the ECG and vitals first." } } ],
    [ { text: { hindi: "एक और रैंडम टेस्ट ऑर्डर कर दो और देखते हैं क्या आता है", english: "Order another random test and see what comes up" },
        reaction: { hindi: "रिया, बिना सोचे सारे टेस्ट करवाना मरीज़ और अस्पताल दोनों के लिए ठीक नहीं। उलझन हो तो सीनियर से कंसल्ट करो।", english: "Riya, running every test without thinking is not good for the patient or the hospital. If confused, consult a senior." } },
      { text: { hindi: "सिक्का उछालकर तय करो - हेड्स पर इलाज A, टेल्स पर इलाज B", english: "Flip a coin - heads for treatment A, tails for treatment B" },
        reaction: { hindi: "रिया, मेडिकल फ़ैसले सिक्के से नहीं, सबूत और सीनियर की सलाह से होते हैं! सिक्का कैंटीन में चाय के लिए रखो।", english: "Riya, medical decisions are made with evidence and senior advice, not coins! Keep the coin for the canteen chai." } } ],
    [ { text: { hindi: "उनसे कहो कि मेडिकल शब्द बहुत मुश्किल हैं, आप समझ नहीं पाओगे", english: "Tell them the medical terms are too difficult, they won't understand" },
        reaction: { hindi: "रिया, मुश्किल बात को आसान भाषा में समझाना ही डॉक्टर का काम है। शांति से सच बताओ, जितना पक्का हो उतना।", english: "Riya, explaining hard things in simple words is a doctor's job. Tell the truth calmly, as much as you're sure of." } },
      { text: { hindi: "उन्हें चाय पिलाओ और कहो कि चाय के साथ टेंशन अपने आप चली जाती है", english: "Give them a cup of chai and say tension disappears with tea" },
        reaction: { hindi: "रिया, चाय से दिल को सुकून मिलता है, पर परिवार को सही जानकारी चाहिए। पहले सच बताओ, चाय बाद में।", english: "Riya, chai soothes the heart, but the family needs the right information. Truth first, chai later." } } ],
    [ { text: { hindi: "पहले पूरी फ़ाइल और इंश्योरेंस का पेपरवर्क पूरा करवाओ, फिर ऑपरेशन की तैयारी करो", english: "First get the full file and insurance paperwork done, then prepare for the operation" },
        reaction: { hindi: "रिया, इमरजेंसी में पेपरवर्क बाद में - मरीज़ की जान पहले। टीम को तुरंत अलर्ट करना ज़रूरी है।", english: "Riya, in an emergency paperwork comes later - the patient's life comes first. Alerting the team immediately is essential." } },
      { text: { hindi: "टीम को WhatsApp ग्रुप में मैसेज करो और ब्लू टिक का इंतज़ार करो", english: "Message the team on WhatsApp and wait for the blue tick" },
        reaction: { hindi: "रिया, WhatsApp पर ब्लू टिक का इंतज़ार करने से मरीज़ का BP नहीं सुधरता! इमरजेंसी में सीधे कॉल करो और टीम को अलर्ट करो।", english: "Riya, waiting for a blue tick won't improve the patient's BP! In an emergency, call directly and alert the team." } } ],
    [ { text: { hindi: "थोड़ी कॉफ़ी पीकर ड्यूटी के लिए खुद को पुश करो, थकान को नज़रअंदाज़ करो", english: "Push yourself with some coffee and ignore the tiredness" },
        reaction: { hindi: "रिया, थकान को कॉफ़ी से ढकना आराम नहीं होता। थके डॉक्टर से गलतियाँ होती हैं - थोड़ी देर आराम करो।", english: "Riya, covering tiredness with coffee isn't rest. A tired doctor makes mistakes - rest a little." } },
      { text: { hindi: "OT की टेबल पर लेटकर सो जाओ, वही सबसे आरामदायक जगह है", english: "Lie down and sleep on the OT table, it's the comfiest place" },
        reaction: { hindi: "रिया, OT टेबल मरीज़ की होती है, डॉक्टर का बिस्तर नहीं! रेस्ट रूम में जाओ और थोड़ा आराम करो।", english: "Riya, the OT table is for patients, not a doctor's bed! Go to the rest room and take a little rest." } } ]
  ]
};

let extraChoicesApplied = false;

function applyExtraChoices() {
  if (extraChoicesApplied) return;      // safety: never add them twice
  extraChoicesApplied = true;

  Object.keys(extraChoices).forEach(function (storyId) {
    const story = storiesData[storyId];
    if (!story) return;

    extraChoices[storyId].forEach(function (list, epIndex) {
      const ep = story.episodes[epIndex];
      if (!ep) return;

      // The character who reacts to the original wrong choice also
      // reacts to the extra choices (same speaker + avatar).
      const wrongBase = ep.choices.find(function (c) { return !c.correct; }) || ep.choices[0];

      list.forEach(function (extra) {
        ep.choices.push({
          text: extra.text,
          correct: false,
          funny: extra.funny === true,
          skills: { technical: 0, communication: 0, problemSolving: 0, leadership: 0 },
          reaction: { speaker: wrongBase.reaction.speaker, avatar: wrongBase.reaction.avatar, text: extra.reaction }
        });
      });
    });
  });

  // Translations (only the doctor story has them)
  if (typeof storyTranslations !== "undefined") {
    Object.keys(extraTranslations).forEach(function (storyId) {
      const tr = storyTranslations[storyId];
      if (!tr) return;
      extraTranslations[storyId].forEach(function (list, epIndex) {
        const epTr = tr.episodes[epIndex];
        if (!epTr) return;
        list.forEach(function (c) { epTr.choices.push(c); });
      });
    });
  }
}

applyExtraChoices();
